"""empty message

Revision ID: 0b8a96a3c36d
Revises: 
Create Date: 2020-10-07 19:07:27.115383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8a96a3c36d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('photoUrl', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('photoUrl', sa.String(), nullable=True),
    sa.Column('release', sa.DateTime(), nullable=False),
    sa.Column('genres', sa.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('types', sa.String(), nullable=False),
    sa.Column('movie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie'], ['Movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actors_for_roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['Actors.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'actor_id')
    )
    op.create_table('roles_in_movies',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['Movies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], ),
    sa.PrimaryKeyConstraint('movie_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_in_movies')
    op.drop_table('actors_for_roles')
    op.drop_table('Roles')
    op.drop_table('Movies')
    op.drop_table('Actors')
    # ### end Alembic commands ###
