"""empty message

Revision ID: 9c0b36e77224
Revises: 0b8a96a3c36d
Create Date: 2020-10-08 22:20:34.723212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0b36e77224'
down_revision = '0b8a96a3c36d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Roles', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.drop_constraint('Roles_movie_fkey', 'Roles', type_='foreignkey')
    op.create_foreign_key(None, 'Roles', 'Movies', ['movie_id'], ['id'])
    op.drop_column('Roles', 'movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Roles', sa.Column('movie', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Roles', type_='foreignkey')
    op.create_foreign_key('Roles_movie_fkey', 'Roles', 'Movies', ['movie'], ['id'])
    op.drop_column('Roles', 'movie_id')
    # ### end Alembic commands ###
